

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

#  mongo:
#    image: mongo:6
#    ports:
#      - "27017:27017"
